### ISSUE TITLE
[BUG] God Mode Command

### ISSUE THREAD

**Issue by Blankked** [FINE-V3rm/Core#3]
**Describe the bug**
When attempting to god mode an online player, no response is given.

**To Reproduce**
1.  /god (online player)
2. See error

**Expected behavior**
Nothing will happen

**Screenshots**
https://pays.host/uploads/a0fee455-f32e-44bf-8622-bf6508b64aee/AadUBqp0.png 
(command sent)

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client Version: Lunar 1.16.5
 - Core Version: dev build

**Additional context**
Not certain if the command still works or not, as /ungod is still being fixed.

**Comment by FINE-V3rm** [comment]
Issue identified, seems I forgot to add a message if you god an online player. Command should still work, will make a fix later today

**Comment by Blankked** [comment]
Additionally, there is no error message when a player without permissions attempts to godmode themselves or another player

**Comment by FINE-V3rm** [comment]
Noted, will fix both of these soon

**Comment by FINE-V3rm** [comment]
Fixed https://github.com/FINE-V3rm/Core/commit/51ab1420e4bbf5d4de74050ce2e0e1f89dd679d9
