### ISSUE TITLE
[BUG] Feed Command

### ISSUE THREAD

**Issue by Blankked** [FINE-V3rm/Core#4]
**Describe the bug**
 When attempting to feed another player or an offline player, the player who sent the command is the one who gets fed 

**To Reproduce**
1. /feed (online/offline player)
2. See error

**Expected behavior**
You can expect the player who sent the command to be fed, while nothing happens to the player it was directed at 

**Screenshots**
https://pays.host/uploads/a0fee455-f32e-44bf-8622-bf6508b64aee/eJR4urYn.png
(same thing applies to online players)

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client Version: Lunar 1.16.5
 - Core Version: dev build

**Comment by FINE-V3rm** [comment]
this is due to /heal and feed not having player support, fixed when i rewrtie basic commands

**Comment by FINE-V3rm** [comment]
Fixed https://github.com/FINE-V3rm/Core/commit/51ab1420e4bbf5d4de74050ce2e0e1f89dd679d9
