### ISSUE TITLE
[BUG] CumWand and GiveCum Commands

### ISSUE THREAD

**Issue by Blankked** [FINE-V3rm/Core#5]
**Describe the bug**
No message is sent in chat when you /givecum (another online player) or /cumwand (another online player)

**To Reproduce**
1. /givecum (another online player) or /cumwand (another online player)
2. See error

**Expected behavior**
The provided player will receive the cumwand, but no confirming message is sent to the player that issued the command. However, the player receiving the cumwand will receive the "Gave you the cumwand" message.

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client Version: Lunar 1.16.5
 - Core Version: dev build

**Comment by Blankked** [comment]
Same applies to /cumcheck

**Comment by FINE-V3rm** [comment]
Fixed https://github.com/FINE-V3rm/Core/commit/51ab1420e4bbf5d4de74050ce2e0e1f89dd679d9
